//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetUniversalPatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetUniversalPatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Action: 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Action_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Action_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Instruction 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Add_Instruction_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Add_Instruction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Target 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Add_Target_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Add_Target_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Add_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_BtnSave_Update_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_BtnSave_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Cancel_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Clear_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Clear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Target 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Edit_Target_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Edit_Target_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Edit_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Name: 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Full_Name_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Full_Name_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Index_HeaderText {
            get {
                return ResourceManager.GetString("FrmAddTarget_Index_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index: 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Index_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Index_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instructions 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Instructions_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Instructions_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Down 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Move_Down_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Move_Down_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Up 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Move_Up_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Move_Up_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpCode 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_OpCode_HeaderText {
            get {
                return ResourceManager.GetString("FrmAddTarget_OpCode_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpCode: 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_OpCode_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_OpCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operand 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Operand_HeaderText {
            get {
                return ResourceManager.GetString("FrmAddTarget_Operand_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operand: 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Operand_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Operand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional: 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Optional_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Optional_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Remove_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Save_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_Target_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_Target_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_TsmiEditInstruction_Update_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_TsmiEditInstruction_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string FrmAddTarget_TsmiRemoveInstruction_AddTarget_Text {
            get {
                return ResourceManager.GetString("FrmAddTarget_TsmiRemoveInstruction_AddTarget_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string FrmMain_About_Text {
            get {
                return ResourceManager.GetString("FrmMain_About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Author_Text {
            get {
                return ResourceManager.GetString("FrmMain_Author_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Exit_Text {
            get {
                return ResourceManager.GetString("FrmMain_Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make Backup 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Make_Backup_Text {
            get {
                return ResourceManager.GetString("FrmMain_Make_Backup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patch 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Patch_Text {
            get {
                return ResourceManager.GetString("FrmMain_Patch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patcher Info 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Patcher_Info_Text {
            get {
                return ResourceManager.GetString("FrmMain_Patcher_Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Refresh_Text {
            get {
                return ResourceManager.GetString("FrmMain_Refresh_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Release Date: 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Release_Date_Text {
            get {
                return ResourceManager.GetString("FrmMain_Release_Date_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Release Info 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Release_Info_Text {
            get {
                return ResourceManager.GetString("FrmMain_Release_Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Editor 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Script_Editor_Text {
            get {
                return ResourceManager.GetString("FrmMain_Script_Editor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log 的本地化字符串。
        /// </summary>
        internal static string FrmMain_SetLogVisible_Log_Text {
            get {
                return ResourceManager.GetString("FrmMain_SetLogVisible_Log_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software: 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Software_Text {
            get {
                return ResourceManager.GetString("FrmMain_Software_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Files ({0}): 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Target_Files_Text {
            get {
                return ResourceManager.GetString("FrmMain_Target_Files_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Website: 的本地化字符串。
        /// </summary>
        internal static string FrmMain_Website_Text {
            get {
                return ResourceManager.GetString("FrmMain_Website_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About Text: 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_About_Text_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_About_Text_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Placeholder 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Add_Placeholder_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Add_Placeholder_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Add_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Author_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Author_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder Key is empty! 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_BtnAddPlaceholder_Placeholder_Key_is_empty_Msg {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_BtnAddPlaceholder_Placeholder_Key_is_empty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder Value is empty! 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_BtnAddPlaceholder_Placeholder_Value_is_empty_Msg {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_BtnAddPlaceholder_Placeholder_Value_is_empty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_BtnAddPlaceholder_Update_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_BtnAddPlaceholder_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patcher Options are successfully saved! 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_BtnSave_Patcher_Options_are_successfully_saved_Msg {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_BtnSave_Patcher_Options_are_successfully_saved_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; Placeholder already exists! 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_BtnSave_Placeholder_already_exists_Msg {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_BtnSave_Placeholder_already_exists_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software Name is empty! 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_BtnSave_Software_Name_is_empty_Msg {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_BtnSave_Software_Name_is_empty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Cancel_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Clear_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Clear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Edit_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make Backup 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Make_Backup_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Make_Backup_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Down 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Move_Down_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Move_Down_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Up 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Move_Up_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Move_Up_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Options_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Options_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patcher Info 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Patcher_Info_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Patcher_Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patcher Options 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Patcher_Options_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Patcher_Options_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder Key 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Placeholder_Key_HeaderText {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Placeholder_Key_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder Key: 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Placeholder_Key_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Placeholder_Key_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder Value 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Placeholder_Value_HeaderText {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Placeholder_Value_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder Value: 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Placeholder_Value_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Placeholder_Value_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholders 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Placeholders_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Placeholders_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Release Date: 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Release_Date_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Release_Date_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Release Info: 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Release_Info_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Release_Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Remove_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Remove_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved Placeholders 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Reserved_Placeholders_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Reserved_Placeholders_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Save_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software: 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Software_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Software_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Today_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Today_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visit 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Visit_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Visit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Website: 的本地化字符串。
        /// </summary>
        internal static string FrmPatcherOptions_Website_Text {
            get {
                return ResourceManager.GetString("FrmPatcherOptions_Website_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_About_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action Method 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Action_Method_HeaderText {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Action_Method_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Target File 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Add_Target_File_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Add_Target_File_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_AddPatch_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_AddPatch_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_AddTargetFile_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_AddTargetFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target File Path is empty! 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_BtnAddTargetFile_Target_File_Path_is_empty_Msg {
            get {
                return ResourceManager.GetString("FrmScriptEditor_BtnAddTargetFile_Target_File_Path_is_empty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove &quot;{0}&quot;? 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_BtnRemovePatch_Msg {
            get {
                return ResourceManager.GetString("FrmScriptEditor_BtnRemovePatch_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_btnSave_Update_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_btnSave_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indices are empty! -&gt; {0} 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_CheckScript_Indices_are_empty_Msg {
            get {
                return ResourceManager.GetString("FrmScriptEditor_CheckScript_Indices_are_empty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instructions are Empty!
        ///Target -&gt; {0} 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_CheckScript_Instructions_are_Empty_Msg {
            get {
                return ResourceManager.GetString("FrmScriptEditor_CheckScript_Instructions_are_Empty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patch List is Empty! 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_CheckScript_Patch_List_is_Empty_Msg {
            get {
                return ResourceManager.GetString("FrmScriptEditor_CheckScript_Patch_List_is_Empty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder Key is empty!
        ///Placeholder Value -&gt; &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_CheckScript_Placeholder_Key_is_empty_Msg {
            get {
                return ResourceManager.GetString("FrmScriptEditor_CheckScript_Placeholder_Key_is_empty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target List is Empty! 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_CheckScript_Target_List_is_Empty_Msg {
            get {
                return ResourceManager.GetString("FrmScriptEditor_CheckScript_Target_List_is_Empty_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Close_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Close_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_EditTarget_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_EditTarget_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_EditTargetFile_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_EditTargetFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Path 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_File_Path_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_File_Path_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_File_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_File_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Full Name 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Full_Name_HeaderText {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Full_Name_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep Old MaxStack Value 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Keep_Old_MaxStack_Value_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Keep_Old_MaxStack_Value_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Down 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_MoveDownTarget_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_MoveDownTarget_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Up 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_MoveUpTarget_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_MoveUpTarget_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_New_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_New_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Open_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Open_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Options_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Options_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patch List 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Patch_List_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Patch_List_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patcher Options 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Patcher_Options_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Patcher_Options_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_RemoveTarget_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_RemoveTarget_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_RemoveTargetFile_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_RemoveTargetFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As... 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Save_As_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Save_As_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Save_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Editor 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Script_Editor_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Script_Editor_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Files 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Target_Files_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Target_Files_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Info 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Target_Info_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Target_Info_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target List 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Target_List_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Target_List_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target Options 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_Target_Options_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_Target_Options_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to save changes before closing the script file? 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_TsmiCloseScript_Message {
            get {
                return ResourceManager.GetString("FrmScriptEditor_TsmiCloseScript_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Target 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_TsmiEditTarget_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_TsmiEditTarget_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_TsmiEditTargetFile_Update_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_TsmiEditTargetFile_Update_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patch {0} 的本地化字符串。
        /// </summary>
        internal static string FrmScriptEditor_TsmiOpenScript_PatchName_Text {
            get {
                return ResourceManager.GetString("FrmScriptEditor_TsmiOpenScript_PatchName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete me. 的本地化字符串。
        /// </summary>
        internal static string Helpers_CreatePatcherDirIfNotExists_FileContent {
            get {
                return ResourceManager.GetString("Helpers_CreatePatcherDirIfNotExists_FileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Your DNUP Script Files Here! 的本地化字符串。
        /// </summary>
        internal static string Helpers_CreatePatcherDirIfNotExists_FileName {
            get {
                return ResourceManager.GetString("Helpers_CreatePatcherDirIfNotExists_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instruction not found at offset {0} 的本地化字符串。
        /// </summary>
        internal static string Patcher_GetInstruction_Instruction_not_found_Msg {
            get {
                return ResourceManager.GetString("Patcher_GetInstruction_Instruction_not_found_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backup file already exists -&gt; {0} 的本地化字符串。
        /// </summary>
        internal static string Patcher_Save_Backup_file_already_exists_Msg {
            get {
                return ResourceManager.GetString("Patcher_Save_Backup_file_already_exists_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patchers folder not found. 
        ///{0}{1}{2} 的本地化字符串。
        /// </summary>
        internal static string ScriptEngine_LoadAndParseScripts__DirectoryNotFoundException_Msg {
            get {
                return ResourceManager.GetString("ScriptEngine_LoadAndParseScripts__DirectoryNotFoundException_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error while loading the script file -&gt; ({0})
        ///{1}{2}{3} 的本地化字符串。
        /// </summary>
        internal static string ScriptEngine_LoadAndParseScripts_Exception_Msg {
            get {
                return ResourceManager.GetString("ScriptEngine_LoadAndParseScripts_Exception_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [File Patched] -&gt; {0} 的本地化字符串。
        /// </summary>
        internal static string ScriptEngine_Process__File_Patched_Msg {
            get {
                return ResourceManager.GetString("ScriptEngine_Process__File_Patched_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [File Path] -&gt; {0} {1} 的本地化字符串。
        /// </summary>
        internal static string ScriptEngine_Process__File_Path_Msg {
            get {
                return ResourceManager.GetString("ScriptEngine_Process__File_Path_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Skipping file] 的本地化字符串。
        /// </summary>
        internal static string ScriptEngine_Process__Skipping_file_Msg {
            get {
                return ResourceManager.GetString("ScriptEngine_Process__Skipping_file_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File not found -&gt; {0} 的本地化字符串。
        /// </summary>
        internal static string ScriptEngine_Process_File_not_found_Msg {
            get {
                return ResourceManager.GetString("ScriptEngine_Process_File_not_found_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executable files (.exe;*.dll)|*.exe;*.dll|All files (*.*)|*.* 的本地化字符串。
        /// </summary>
        internal static string ScriptEngine_Process_Filter_ExtName {
            get {
                return ResourceManager.GetString("ScriptEngine_Process_Filter_ExtName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nothing patched! 的本地化字符串。
        /// </summary>
        internal static string ScriptEngine_Process_Nothing_patched_Msg {
            get {
                return ResourceManager.GetString("ScriptEngine_Process_Nothing_patched_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Patching process finished! [{0} file(s) patched] 的本地化字符串。
        /// </summary>
        internal static string ScriptEngine_Process_Patching_process_finished_Msg {
            get {
                return ResourceManager.GetString("ScriptEngine_Process_Patching_process_finished_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software Name is empty! 的本地化字符串。
        /// </summary>
        internal static string ScriptEngineHelpers_ValidateScript_Software_Name_is_empty_Msg {
            get {
                return ResourceManager.GetString("ScriptEngineHelpers_ValidateScript_Software_Name_is_empty_Msg", resourceCulture);
            }
        }
    }
}
